#!/usr/bin/env ruby

require_relative 'lib/environment'
Environment.environment = ENV["DB"] || "development"

def clean_gets
  (gets || "").chomp
end

def show_view_menu
  puts "View what?\n1. Locations\n2. Landmarks\n3. Journal Entries\n"
end

puts "\n=================\nWelcome Traveler!\n=================\n"
puts "1. New\n2. View\n"

command = clean_gets
case command
when "1"
  show_view_menu
end


